fix: symlink handling

diff --git a/packaging/preinst b/packaging/preinst
--- a/packaging/preinst
+++ b/packaging/preinst
@@ -21,13 +21,13 @@ if ! [ -d "$NEWPATH" ]; then
 fi
 
 if ! [ -L "$OLDPATH" ]; then
+    if [ -d "$OLDPATH" ]; then
+        mv "$OLDPATH"/* "$NEWPATH" || abort "Failed to copy DynamicLibraries to TweakInject"
+        rm -rf "$OLDPATH" || abort "Failed to remove DynamicLibraries"
+    fi
     if [ -e "$OLDPATH" ]; then
         # WTF?
         abort "DynamicLibraries exists and is not a symlink"
-    fi
-    if [ -d "$OLDPATH" ]; then
-        mv -a "$OLDPATH"/* "$NEWPATH" || abort "Failed to copy DynamicLibraries to TweakInject"
-        rm -rf "$OLDPATH" || abort "Failed to remove DynamicLibraries"
     fi
     mkdir -p "@INSTALL_PREFIX@/Library/MobileSubstrate" || abort "Failed to create MobileSubstrate directory"
     ln -s "$NEWPATH" "$OLDPATH" || abort "Failed to symlink DynamicLibraries to TweakInject"
